# SearXNG configuration for Firecrawl
use_default_settings: true

server:
  secret_key: "${SEARXNG_SECRET_KEY:-change_this_secret_key_in_production}"

search:
  safe_search: 0
  default_lang: "en"
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg